### ISSUE TITLE
Refactor high complexity function 1

### ISSUE THREAD

**Issue by nwessman** [DD2480-Group-11/litiengine#4]
For P+:

3. You carry out some of Task 3: you refactor at least two of the functions (per group) with high cyclomatic
complexity to reduce it by at least 35 % (for example, by splitting the functions).

**Comment by danhalv** [comment]
I can have a look at the function addEntity in Environments.java that I made a refactor plan for.

**Comment by danhalv** [comment]
Issue is resolved. The refactor can be found here: https://github.com/DD2480-Group-11/litiengine/tree/refactor1
